### PR TITLE
Layout/card list by series

### PR DESCRIPTION
**Pull request by allen84324**
新增Card List by Series跟OfficialProductList到views
image
index.js新增
image
image
App.vue新增
image

### CODE REVIEW

**Review by wuuhua — APPROVED** [review]
OK 但之後應該會需要修改App.vue 內容會拿掉

**Review by YuCheng07 — APPROVED** [review]
ok

**Review by minjuilu — APPROVED** [review]
path: "/Card List by Series",
 
 空格很怪

**Review by Wandaihsien — APPROVED** [review]

**Comment by wuuhua** [comment]
應該用-或_連接path name

**Review by Kenny1238 — APPROVED** [review]

**Review by Enya-Wu — APPROVED** [review]

**Pull request merged**
